services:
  # Web service configuration
  - type: web
    name: Medical_Reports_Text_Extraction
    runtime: docker
    plan: starter # Choose an appropriate plan
    
    # Environment specific settings
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: TESSERACT_PATH
        value: /opt/homebrew/bin/tesseract
      - key: UPLOAD_DIR  # Add this
        value: /app/uploads
    
    # Persistent disk for storing uploaded images
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 1
      
    # Health check
    healthCheckPath: /
    
    # Auto-deploy settings
    autoDeploy: true